export type MbtiAxis = "EI" | "SN" | "TF" | "JP";

export interface MbtiScenario {
  id: string;
  axis: MbtiAxis;
  prompt: string;
  firstIndicators: string[];
  secondIndicators: string[];
}

export const MBTI_SCENARIOS: MbtiScenario[] = [
  // === E/I Axis (4 scenarios) ===
  {
    id: "ei-1",
    axis: "EI",
    prompt:
      "You're starting a new complex project. Would you prefer to brainstorm with a large group of people first, or would you rather spend time alone researching and forming your own ideas before discussing with others? Describe your ideal approach.",
    firstIndicators: [
      "group",
      "team",
      "brainstorm",
      "discuss",
      "collaborate",
      "together",
      "meeting",
      "everyone",
      "crowd",
      "social",
      "talk",
      "share ideas",
      "bounce off",
    ],
    secondIndicators: [
      "alone",
      "myself",
      "quiet",
      "think",
      "research",
      "reflect",
      "solitude",
      "independent",
      "deep dive",
      "focus",
      "private",
      "contemplate",
      "internal",
    ],
  },
  {
    id: "ei-2",
    axis: "EI",
    prompt:
      "After a long day of intense problem-solving, what would recharge you more: joining a lively discussion group about interesting topics, or spending quiet time reading and processing what you learned? Explain why.",
    firstIndicators: [
      "discussion",
      "lively",
      "people",
      "energize",
      "social",
      "conversation",
      "interact",
      "engage",
      "stimulat",
      "group",
      "others",
      "community",
    ],
    secondIndicators: [
      "quiet",
      "read",
      "alone",
      "recharge",
      "peace",
      "solitude",
      "rest",
      "reflect",
      "space",
      "calm",
      "introvert",
      "decompress",
      "wind down",
    ],
  },
  {
    id: "ei-3",
    axis: "EI",
    prompt:
      "When explaining a complex concept, do you prefer to think out loud and refine your ideas through conversation, or do you prefer to fully formulate your thoughts internally before sharing a polished explanation?",
    firstIndicators: [
      "out loud",
      "conversation",
      "talk through",
      "discuss",
      "verbal",
      "refine through",
      "dialogue",
      "interactive",
      "back and forth",
      "speaking",
    ],
    secondIndicators: [
      "internally",
      "formulate",
      "polished",
      "prepared",
      "think first",
      "organize thought",
      "before sharing",
      "carefully",
      "fully formed",
      "complete",
    ],
  },
  {
    id: "ei-4",
    axis: "EI",
    prompt:
      "You have a free weekend. Would you organize a hackathon with many participants or work on a personal side project in a quiet environment? Describe what appeals to you about your choice.",
    firstIndicators: [
      "hackathon",
      "participants",
      "organize",
      "event",
      "people",
      "team",
      "competition",
      "social",
      "network",
      "community",
      "gather",
    ],
    secondIndicators: [
      "personal",
      "side project",
      "quiet",
      "own pace",
      "alone",
      "solo",
      "focused",
      "peaceful",
      "private",
      "undisturbed",
    ],
  },

  // === S/N Axis (4 scenarios) ===
  {
    id: "sn-1",
    axis: "SN",
    prompt:
      "When learning a new programming language, do you prefer to start with practical tutorials and real-world examples, or do you prefer to first understand the theoretical foundations and design philosophy behind the language?",
    firstIndicators: [
      "practical",
      "tutorial",
      "example",
      "hands-on",
      "real-world",
      "concrete",
      "step by step",
      "applied",
      "build something",
      "code first",
      "try it",
    ],
    secondIndicators: [
      "theor",
      "philosophy",
      "design",
      "concept",
      "abstract",
      "understand why",
      "foundation",
      "principle",
      "paradigm",
      "big picture",
      "pattern",
      "underlying",
    ],
  },
  {
    id: "sn-2",
    axis: "SN",
    prompt:
      "A user reports a bug. Do you go straight to the logs and error messages to trace the specific issue, or do you first think about the system architecture and hypothesize about what category of problems could cause such behavior?",
    firstIndicators: [
      "logs",
      "error message",
      "trace",
      "specific",
      "reproduce",
      "stack trace",
      "debug",
      "data",
      "evidence",
      "concrete",
      "step through",
      "actual",
    ],
    secondIndicators: [
      "architect",
      "hypothes",
      "category",
      "pattern",
      "systemic",
      "root cause",
      "broader",
      "mental model",
      "theory",
      "possibility",
      "what if",
      "imagine",
    ],
  },
  {
    id: "sn-3",
    axis: "SN",
    prompt:
      "When describing a software system to someone, do you focus on specific features, APIs, and concrete functionality, or do you focus on the overall vision, architectural patterns, and how it fits into the bigger technological landscape?",
    firstIndicators: [
      "specific",
      "feature",
      "API",
      "function",
      "concrete",
      "detail",
      "endpoint",
      "implementation",
      "technical spec",
      "measurable",
      "tangible",
    ],
    secondIndicators: [
      "vision",
      "architect",
      "pattern",
      "landscape",
      "big picture",
      "concept",
      "philosophy",
      "abstract",
      "metaphor",
      "narrative",
      "transform",
      "future",
    ],
  },
  {
    id: "sn-4",
    axis: "SN",
    prompt:
      "You're choosing between two job offers. Company A gives you detailed metrics about salary, benefits, and project specs. Company B shares their ambitious 10-year vision to revolutionize their industry. Which presentation style resonates more with you and why?",
    firstIndicators: [
      "metrics",
      "salary",
      "benefit",
      "detail",
      "specific",
      "concrete",
      "number",
      "practical",
      "tangible",
      "clear",
      "defined",
      "stable",
    ],
    secondIndicators: [
      "vision",
      "ambitious",
      "revolutionize",
      "potential",
      "future",
      "inspire",
      "mission",
      "dream",
      "transform",
      "innovate",
      "possibility",
      "imagine",
    ],
  },

  // === T/F Axis (4 scenarios) ===
  {
    id: "tf-1",
    axis: "TF",
    prompt:
      "A team member's code has a critical bug in production. They're clearly stressed and upset. How do you handle the situation? Focus on your priorities in responding.",
    firstIndicators: [
      "fix",
      "root cause",
      "prevent",
      "process",
      "analyz",
      "logic",
      "systematic",
      "efficient",
      "postmortem",
      "review",
      "objective",
      "solution",
      "technical",
    ],
    secondIndicators: [
      "feeling",
      "stress",
      "support",
      "reassure",
      "empathy",
      "comfort",
      "emotional",
      "okay",
      "understand",
      "happen to everyone",
      "care",
      "wellbeing",
      "human",
    ],
  },
  {
    id: "tf-2",
    axis: "TF",
    prompt:
      "You need to choose between two technical solutions: Solution A is objectively more efficient and performant, but the team strongly prefers Solution B because they find it more intuitive and enjoyable to work with. Which do you choose and why?",
    firstIndicators: [
      "efficient",
      "performan",
      "objective",
      "metric",
      "data",
      "optimal",
      "rational",
      "best solution",
      "technically",
      "measure",
      "benchmark",
      "superior",
    ],
    secondIndicators: [
      "team prefer",
      "intuitive",
      "enjoy",
      "morale",
      "happy",
      "comfortable",
      "consensus",
      "buy-in",
      "motivation",
      "people",
      "satisfaction",
      "harmony",
    ],
  },
  {
    id: "tf-3",
    axis: "TF",
    prompt:
      "You're writing a code review. The code works but is poorly structured. How do you frame your feedback? Walk me through your approach to delivering the review.",
    firstIndicators: [
      "direct",
      "specific",
      "issue",
      "problem",
      "improve",
      "standard",
      "principle",
      "correct",
      "should",
      "must",
      "objectively",
      "clear feedback",
    ],
    secondIndicators: [
      "constructive",
      "positive",
      "sandwich",
      "appreciate",
      "gentle",
      "encourage",
      "tactful",
      "diplomatic",
      "relationship",
      "tone",
      "kind",
      "supportive",
    ],
  },
  {
    id: "tf-4",
    axis: "TF",
    prompt:
      "A promising new hire is struggling to keep up. Letting them go would be better for team productivity, but you know they have potential and personal circumstances making things hard. What's your recommendation?",
    firstIndicators: [
      "productiv",
      "performance",
      "deadline",
      "deliver",
      "business",
      "objective",
      "standard",
      "efficiency",
      "bottom line",
      "result",
      "let go",
      "replace",
    ],
    secondIndicators: [
      "potential",
      "circumstance",
      "support",
      "mentor",
      "patience",
      "invest",
      "compassion",
      "understanding",
      "human",
      "chance",
      "help",
      "grow",
      "personal",
    ],
  },

  // === J/P Axis (4 scenarios) ===
  {
    id: "jp-1",
    axis: "JP",
    prompt:
      "How do you approach planning a software project? Do you create detailed roadmaps, milestones, and schedules upfront, or do you prefer to start building quickly and adapt your plan as you learn more? Describe your preferred workflow.",
    firstIndicators: [
      "roadmap",
      "milestone",
      "schedule",
      "plan",
      "deadline",
      "structure",
      "organize",
      "timeline",
      "upfront",
      "defined",
      "systematic",
      "phase",
    ],
    secondIndicators: [
      "adapt",
      "flexible",
      "iterate",
      "agile",
      "evolve",
      "explore",
      "organic",
      "spontaneous",
      "pivot",
      "discover",
      "flow",
      "adjust",
      "start building",
    ],
  },
  {
    id: "jp-2",
    axis: "JP",
    prompt:
      "It's Monday morning. Do you plan your entire week's tasks with specific time blocks, or do you keep a loose list and tackle things based on what feels most important in the moment? Why does this approach work for you?",
    firstIndicators: [
      "plan",
      "time block",
      "schedule",
      "calendar",
      "organize",
      "structure",
      "routine",
      "prioritize list",
      "systematic",
      "order",
      "prepare",
      "discipline",
    ],
    secondIndicators: [
      "loose",
      "flexible",
      "moment",
      "feel",
      "spontaneous",
      "flow",
      "adapt",
      "open",
      "intuition",
      "freedom",
      "opportunity",
      "go with",
    ],
  },
  {
    id: "jp-3",
    axis: "JP",
    prompt:
      "You're working on a feature and discover an interesting tangential problem. Do you note it for later and stay focused on your current task, or do you explore it now because it might lead to something valuable? Explain your reasoning.",
    firstIndicators: [
      "note it",
      "later",
      "focus",
      "current task",
      "stay on track",
      "priorit",
      "finish first",
      "disciplin",
      "scope",
      "backlog",
      "complete",
      "commit",
    ],
    secondIndicators: [
      "explore",
      "tangent",
      "curious",
      "interesting",
      "discover",
      "follow",
      "opportunity",
      "might lead",
      "dive in",
      "serendipity",
      "rabbit hole",
      "flexible",
    ],
  },
  {
    id: "jp-4",
    axis: "JP",
    prompt:
      "Your project deadline is in two weeks. Do you prefer to finish early with buffer time for polish and edge cases, or do you work best under pressure and use the full time to explore the best possible solution? Be honest about your style.",
    firstIndicators: [
      "early",
      "buffer",
      "ahead",
      "polish",
      "prepare",
      "safety",
      "margin",
      "comfortable",
      "predictab",
      "reliable",
      "plan",
      "steady",
    ],
    secondIndicators: [
      "pressure",
      "full time",
      "last minute",
      "thrill",
      "deadline",
      "adrenaline",
      "best under",
      "push",
      "freedom",
      "explore",
      "maximize",
      "creative",
    ],
  },
];

export const MBTI_TYPE_DESCRIPTIONS: Record<string, { title: string; description: string; emoji: string }> = {
  INTJ: {
    title: "The Architect",
    description: "Strategic, independent, and driven by logic. You build systems with long-term vision and have little patience for inefficiency. You probably refactor code for fun.",
    emoji: "🏗️",
  },
  INTP: {
    title: "The Logician",
    description: "Analytical, curious, and endlessly questioning. You love exploring theoretical frameworks and finding elegant solutions. Bugs are puzzles, not problems.",
    emoji: "🔬",
  },
  ENTJ: {
    title: "The Commander",
    description: "Bold, decisive, and natural leader. You drive projects forward with confidence and expect excellence. Your code reviews are legendary.",
    emoji: "👑",
  },
  ENTP: {
    title: "The Debater",
    description: "Inventive, quick-witted, and always challenging the status quo. You'd rather build something novel than follow best practices. Convention is just a suggestion.",
    emoji: "⚡",
  },
  INFJ: {
    title: "The Advocate",
    description: "Insightful, principled, and quietly determined. You write code that considers the human impact and advocate for user-centric design. You're the conscience of the team.",
    emoji: "🌟",
  },
  INFP: {
    title: "The Mediator",
    description: "Idealistic, creative, and guided by values. You bring artistic sensibility to technical work and care deeply about meaningful projects. Code should be beautiful.",
    emoji: "🎨",
  },
  ENFJ: {
    title: "The Protagonist",
    description: "Charismatic, empathetic, and inspiring. You mentor junior developers, lead by example, and build team culture. The team is the product.",
    emoji: "🌈",
  },
  ENFP: {
    title: "The Campaigner",
    description: "Enthusiastic, creative, and full of possibilities. You start ten projects because every idea is exciting. Finishing them is... a work in progress.",
    emoji: "🚀",
  },
  ISTJ: {
    title: "The Logistician",
    description: "Reliable, thorough, and methodical. You write tests before code, document everything, and your git history is a masterpiece. Consistency is king.",
    emoji: "📋",
  },
  ISFJ: {
    title: "The Defender",
    description: "Dedicated, warm, and protective. You maintain legacy systems with care, help teammates without being asked, and write the documentation nobody else will.",
    emoji: "🛡️",
  },
  ESTJ: {
    title: "The Executive",
    description: "Organized, direct, and results-oriented. You run standups that actually end on time and your Jira board is immaculate. Shipping is the only metric.",
    emoji: "📊",
  },
  ESFJ: {
    title: "The Consul",
    description: "Supportive, social, and harmony-seeking. You organize team events, remember everyone's birthday, and make sure no one gets left behind in code reviews.",
    emoji: "🤝",
  },
  ISTP: {
    title: "The Virtuoso",
    description: "Practical, observant, and hands-on. You debug by feel, build tools for fun, and can fix anything. Your dotfiles are a work of art.",
    emoji: "🔧",
  },
  ISFP: {
    title: "The Adventurer",
    description: "Flexible, charming, and creative. You bring aesthetic sensibility to UI work and prefer learning by doing. Every project is a chance to express yourself.",
    emoji: "🎭",
  },
  ESTP: {
    title: "The Entrepreneur",
    description: "Energetic, perceptive, and action-oriented. You move fast, ship MVPs, and iterate. Analysis paralysis is for other people.",
    emoji: "💪",
  },
  ESFP: {
    title: "The Entertainer",
    description: "Spontaneous, energetic, and fun-loving. You make standups entertaining, pair program with enthusiasm, and bring energy to every sprint.",
    emoji: "🎉",
  },
};
